global using System.Net;
global using System.Text.Json;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using Moq;
global using Moq.Protected;
global using RecurPixel.Notify;
global using RecurPixel.Notify.Channels;
global using RecurPixel.Notify.Configuration;