source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-relative-links"
gem "jekyll-include-cache"
gem "faraday-retry"
